services:
  backend:
    volumes:
      - .:/workspace:cached
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/workspace/backend/target
      - ./frontend/src/constants:/frontend_constants
    working_dir: /workspace/backend
    command: ["cargo", "watch", "-x", "run"]
    env_file:
      - .env

  frontend:
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/frontend/node_modules
    env_file:
      - .env
    environment:
      - VITE_API_SHARE_URL=http://localhost:5173
      - VITE_API_BASE_URL=http://localhost:8080
    
    working_dir: /workspace/frontend
    
    command: /bin/sh -c "npm install && npm run dev -- --host"

# 名前付きボリュームの定義
volumes:
  cargo-cache:
  target-cache:
  node_modules: